version: '3'
services:
  ros2:
    build:
      context: .
      dockerfile: docker/Dockerfile
    privileged: true
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=0
    volumes:
      - ./ros2_ws:/ros2_ws
      - /dev:/dev
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - "/dev/input"  # コントローラ入力
      - "/dev/video0" # USBカメラ
      - "/dev/ttyUSB0" # Lidar

